### ISSUE TITLE
版本出错

### ISSUE THREAD

**Issue by ly827** [fluttify-project/amap_core_fluttify#2]
**插件版本**

**描述bug**
/usr/local/flutter/bin/flutter --no-color packages get 
拉取版本出错
**复现步骤**
/usr/local/flutter/bin/flutter --no-color packages get
**期望行为**
成功
**截图**
`amap_core_fluttify ^0.0.11+a9797a4 which doesn't match any versions, version solving failed`
**flutter doctor**
/usr/local/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.15-pre.405, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.10.15-pre.405 at /usr/local/flutter
    • Framework revision 28b5cc3825 (2 days ago), 2019-11-05 11:50:30 +0100
    • Engine revision 7b968ff95f
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 38.2.2
    • Dart plugin version 191.8423

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 435BE4E6-2AAB-46C6-AD37-067348D1AD29 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

**Comment by yohom** [comment]
<img width="1004" alt="Screen Shot 2019-11-08 at 07 14 44" src="https://user-images.githubusercontent.com/10418364/68435881-759d1480-01f7-11ea-9980-8c7af5a53158.png">
可能是缓存问题，现在应该已经有了，你再试下。 @ly827

**Comment by ly827** [comment]
嗯 过了一夜有了
