### ISSUE TITLE
无法编译release.apk

### ISSUE THREAD

**Issue by kossfun** [fluttify-project/amap_core_fluttify#3]
**插件版本**
0.0.11+a9797a4
**描述bug**
无法编译release.apk
**复现步骤**

**期望行为**

**截图**
![QQ拼音截图20191112212416](https://user-images.githubusercontent.com/49841387/68675603-2d814780-0593-11ea-96b3-80a2fa5541ff.png)

**flutter doctor**

**Comment by ylytddd** [comment]
一样碰到了

**Comment by zhangzhilin1991** [comment]
同样的问题 如何解决？

**Comment by zhangzhilin1991** [comment]
所有插件全部升级到AndroidX，就好了，原因不明

**Comment by jeson-jin** [comment]
Android studio 3.6.2
