### ISSUE TITLE
Android 编译正式包失败

### ISSUE THREAD

**Issue by CyJaySong** [fluttify-project/amap_core_fluttify#6]
**插件版本**
amap_core_fluttify: ^0.5.2+68b910c
**描述bug**
Android 编译正式包失败
**复现步骤**
flutter build apk --release
**期望行为**
自然是修复啦
**截图**
![image](https://user-images.githubusercontent.com/29367599/71792743-d40a3600-3074-11ea-8dbe-f151ca291742.png)
**flutter doctor**
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale
    zh-Hans-IS)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

**Comment by CyJaySong** [comment]
经测试，为插件冲突，很诡秘。。。。。。

**Comment by mrcwl** [comment]
> 经测试，为插件冲突，很诡秘。。。。。。

怎么解决的

**Comment by KClassmate** [comment]
我遇到了同样问题，创建新项目排查插件发现与 sharesdk_plugin: 冲突

**Comment by bookerss** [comment]
同样问题 请问下如何修复

**Comment by CyJaySong** [comment]
@bookerss @mrcwl 创建新项目排查插件。
